### ISSUE TITLE
2.0 DataServiceVersion in breeze.labs.dataservice.sharepoint.js throws errors on Multi-Lookups

### ISSUE THREAD

**Issue by guythomasdavis** [andrewconnell/breeze.js.labs#11]
The error:

[datacontext]  Error saving changes Error: Collection types are only supported in version 3.0 of the OData protocol and higher versions. They are not supported in version 2.0..  

occurs when trying to save data to a multi-lookup SharePoint field. When changing the DataServiceVersion property in the breeze.labs.dataservice.sharepoint.js file to version 3.0 this error goes away and the data is saved with no errors.

I am basing my updates on this post (http://sharepoint.stackexchange.com/questions/84560/updating-lookup-values-with-the-rest-api) where the format of a multi-lookup in the request data is:

'LookupFieldName': { 'results': [1,50,70... array of ids pointing to the related items in the lookup list] }

**Comment by andrewconnell** [comment]
Fixed in 0.6.4
